name: Send Notification

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Escape Title
        id: escapeTitle
        env: 
          TITLE: ${{ github.event.issue.title }}
        run: |
          export title=$(printf "%q" $TITLE |  sed "s/'//g")
          echo "title=$title" >> $GITHUB_OUTPUT
      - name: Escape Body
        id: escapeBody
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          export body=$(echo $BODY |  sed "s/'/''/g")
          echo "body=$body" >> $GITHUB_OUTPUT
      - name: Send notification on issue creation
        if: ${{github.event.issue}}
        run: |
          curl --location --request POST '${{secrets.WEBHOOK_CHAT}}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
                "cardsV2": [
                    {
                        "card": {
                            "header": {
                                "title": "PR: ${{ steps.escapeTitle.outputs.title }}",
                                "subtitle": "By ${{ github.event.issue.user.login }} in Asgardeo JS SDK Repo",
                                "imageUrl": "https://avatars.githubusercontent.com/u/583231?v=4",
                                "imageType": "CIRCLE",
                                "imageAltText": "GitHub Avatar"
                            },
                            "sections": [
                                {
                                    "header": "Issue Details",
                                    "collapsible": false,
                                    "widgets": [
                                        {
                                            "buttonList": {
                                                "buttons": [
                                                    {
                                                        "text": "Open Issue",
                                                        "onClick": {
                                                            "openLink": {
                                                                "url": "${{ github.event.issue.html_url }}"
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            "textParagraph": {
                                                "text": "${{ steps.escapeBody.outputs.body }}"
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                ]
          }'

      - name: Send notification on pull request creation
        if: ${{github.event.pull_request}}
        run: |
            curl --location --request POST '${{secrets.WEBHOOK_CHAT}}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "cardsV2": [
                    {
                        "card": {
                            "header": {
                                "title": 'PR: ${{ github.event.pull_request.title }}',
                                "subtitle": 'By ${{ github.event.pull_request.user.login }} in Asgardeo JS SDK Repo',
                                "imageUrl": "https://avatars.githubusercontent.com/u/583231?v=4",
                                "imageType": "CIRCLE",
                                "imageAltText": "GitHub Avatar"
                            },
                            "sections": [
                                {
                                    "header": "PR Details",
                                    "collapsible": false,
                                    "widgets": [
                                        {
                                            "buttonList": {
                                                "buttons": [
                                                    {
                                                        "text": "Open PR",
                                                        "onClick": {
                                                            "openLink": {
                                                                "url": '${{ github.event.pull_request.html_url }}'
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            "textParagraph": {
                                                "text": '${{ github.event.issue.body }} | tr "'" "\'"'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                ]
            }'
